[package]
name = "asdb-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isocountry = "0.3.2"
ipnetwork = "0.18.0"
serde = {workspace = true, features = ["derive"]}