[package]
name = "asmap-rs"
version = "0.1.0"
description = "Interactive map of internet autonomous systems, organisations and persons"
edition = "2021"

[workspace]
members = [
    "asdb",
    "asdb-models",
    "asdbmaker",
    "georesolve",
    "asmap/frontend",
    "asmap/server",
    "asmap/protocol",
    "test-context",
    "config",
    "leaflet-markercluster",
]

[workspace.package]
edition = "2021"
authors = ["Piotr Konkol"]
repository = "https://github.com/pkonkol/asmap-rs"
license = "MIT"

[workspace.dependencies]
serde = "1.0"
serde_json = "1.0"
tokio = "1.28"

# [[bin]]
# name = "test"
# src = "src/main.rs"


[dependencies]
asdbmaker = { version = "0.1", path = "asdbmaker" }
config = { path = "config" }
clap = { version = "4.3", features = ["derive"] }
tokio = { workspace = true }
