[package]
name = "asmap-rs"
version = "0.1.0"
description = "Interactive map of internet autonomous systems, organisations and persons"

[workspace]
members = [
    "asdbmaker",
    "georesolve",
]

[workspace.package]
edition = "2021"
authors = ["Piotr Konkol"]
repository = "https://github.com/pkonkol/asmap-rs"
license = "MIT"

[workspace.dependencies]
serde = "1.0.160"
serde_json = "1.0.96"
tokio = "1.28.0"

[dependencies]
