[package]
name = "asmap-rs"
version = "0.1.0"
description = "Interactive map of internet autonomous systems, organisations and persons"
edition = "2021"

[workspace]
members = [
    "asdb",
    "asdb-models",
    "asdb-builder",
    "config",
    "georesolve",
    "asmap/frontend",
    "asmap/server",
    "asmap/protocol",
    "test-context",
    "leaflet-markercluster",
]

[workspace.package]
edition = "2021"
authors = ["Piotr Konkol"]
repository = "https://github.com/pkonkol/asmap-rs"
license = "MIT"

[workspace.dependencies]
serde = "1.0"
serde_json = "1.0"
tokio = "1.28"
ipnetwork = "0.18"
mongodb = "2.7"
thiserror = "1.0"
csv = "1.3"
indicatif = "0.17"

[dependencies]
asdb-builder = { version = "0.1", path = "asdb-builder" }
asdb-models = { version = "0.1", path = "asdb-models" }
asdb = { version = "0.1", path = "asdb" }
config = { path = "config" }
clap = { version = "4.3", features = ["derive"] }
indicatif = { workspace = true }
csv = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
