version: '3'
services:
  asmap-db:
    image: "docker.io/bitnami/mongodb:4.4"
    ports:
      - "27017:27017"
    volumes:
      - 'asmap-data:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_PASSWORD=devrootpass
      - MONGODB_USERNAME=devuser
      - MONGODB_PASSWORD=devpass
      - MONGODB_DATABASE=asmap

volumes:
  data-volume:
  asmap-data:
    driver: local

