[package]
name = "asdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.5.0"
tokio = {workspace = true}
geo-types = "0.7.9" 
isocountry = "0.3.2"
ipnetwork = "0.20.0"
serde = {workspace = true}
futures = "0.3.28"
# serde_json = {workspace = true}