[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
gloo-console = "0.2.3"
gloo-net = { version = "0.2.6", features = ["json", "websocket"] }
gloo-utils = "0.1.6"
leaflet = "0.2.2"
log = "0.4.17"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.33"
wasm-logger = "0.2.0"
web-sys = { version = "0.3", features = ["HtmlAnchorElement", "console", "Window", "Document"] }
yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17.0"
asdb-models = { path = "../../asdb-models" }
futures = "0.3.28"
bincode = "1.3.3"
