[build]
target = "index.html"
dist = "../dist"

[[proxy]]
backend = "http://[::1]:8081/api/"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npm install @tailwindcss/cli && npm run build:css"]

[watch]
ignore = ["css/output.css"]
