[package]
name = "asdbmaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.5.0"
whois-rust = { version = "1.5.1", features = ["tokio"] }
serde = {workspace = true}
serde_json = {workspace = true}
tokio = {workspace = true}
