[package]
name = "asdbmaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.5.0"
serde = "1.0.160"
serde_json = "1.0.96"
tokio = "1.28.0"
whois-rust = { version = "1.5.1", features = ["tokio"] }
