version: '3'
services:
  asdbmaker-db:
    image: "docker.io/bitnami/mongodb:4.4"
    ports:
      - "27018:27017"
    volumes:
      - 'asdbmaker-data:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_PASSWORD=devrootpass
      - MONGODB_USERNAME=devuser
      - MONGODB_PASSWORD=devpass
      - MONGODB_DATABASE=asdbmaker

volumes:
  asdbmaker-data:
    driver: local

